[package]
name = "multitool"
edition.workspace = true
license.workspace = true
version.workspace = true
build = "build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
anyhow.workspace = true
eframe = { version = "0.33.3", features = ["default", "persistence", "wgpu"] }
egui_extras = "0.33.3"
image.workspace = true
lineupper.workspace = true
rfd = "0.17"
statter.workspace = true
strum.workspace = true
